language: node_js
node_js:
- '11'
install:
- npm install -g reveal-md
before_deploy:
- mkdir -p build
- reveal-md slides/ --css slides/theme/custom.css -w --static build
- cd build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
