language: node_js
node_js:
- '11'
before_install:
  - sudo apt-get -y install poppler-utils
install:
- npm install -g reveal-md
before_deploy:
- mkdir -p build
- make build-slides
- touch build/.nojekyll
- ls -l build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
